import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dfontSfntRanges, isDfont, extractDfontFace } from '../src/dfont.js';
import { parseSfnt } from '../src/sfnt.js';
import { readFontNames } from '../src/fontnames.js';

/**
 * A `.dfont` FROM A CONTAINER WRITER WE DID NOT WRITE — the anchor
 * `test/dfont.test.ts` does not have.
 *
 * That file's expectations run against `test/helpers/build-dfont.ts`, which
 * transcribes the same section of Inside Macintosh `src/dfont.ts` does: two
 * halves of one understanding, which can agree and both be wrong. This
 * suitcase was written by FontForge, so its resource map is somebody else's
 * reading of the format.
 *
 * See `test/fixtures/fonts/PROVENANCE.md` for the producer, the licence
 * reasoning (Apple's own suitcases cannot be vendored), and — as load-bearing
 * as the rest — the rules this file still does NOT anchor. Regenerate with
 * `npm run gen:dfont`; it is not run by `npm test` and FontForge is not a
 * dependency.
 *
 * WHAT THIS FILE PINS THAT THE BUILDER DOES NOT. Each mutation was applied to
 * `src/dfont.ts` in turn and BOTH dfont suites re-run, so the split says what
 * this file adds rather than merely that something went red. The numbers are
 * MEASURED — a first draft of this table guessed them and was wrong twice:
 *
 *                                                    here  dfont.test.ts
 *   1 resource count is stored MINUS ONE                2        7
 *   2 type count is stored MINUS ONE                    0        9
 *   3 reference list is based on the TYPE LIST,         5        8
 *     not on the map
 *   4 the u24 addresses a LENGTH, so the sfnt           2        4
 *     begins four bytes later
 *   5 faces are selected BY TAG, not by position        0        2
 *
 * **TWO of the five are NOT anchored here, and neither can be by any file
 * FontForge writes** — both for the same structural reason: it emits `sfnt`
 * as type 0 and `FOND` as type 1. Reading the type count raw still yields
 * type 0, and taking type 0 blindly still lands on `sfnt`, so rules 2 and 5
 * survive their mutations against this suitcase. `dfont.test.ts` holds both
 * alone, at 9 and 2 cases, and its hand-built suitcases can order the types
 * freely precisely because they are hand-built. A real Apple suitcase — which
 * carries `FOND`, and often `NFNT` and `POST` — might well order them the
 * other way, which is the one thing this fixture still cannot stand in for.
 * PROVENANCE.md records it as the remaining ceiling.
 */
describe('a real FontForge-written .dfont', () => {
  const bytes = new Uint8Array(
    readFileSync('test/fixtures/fonts/LiberationSans.dfont'));

  // The fixture is regenerated by a tool, not by hand. Without this, a
  // FontForge upgrade that changed the container would silently rewrite what
  // the assertions below are measured against.
  it('is the file these expectations were written against', () => {
    expect(createHash('sha256').update(bytes).digest('hex'))
      .toBe('ee86a00a589577892dc65f501d3c24ccb2aa6d8e5c1f8f8fab444d7b32e7436b');
    expect(bytes.length).toBe(1633529);
  });

  it('is recognised as a suitcase at all', () => {
    // Detection is STRUCTURAL — a .dfont has no signature, it opens with a raw
    // u32 data offset — so this asserts the walk survives real bytes rather
    // than a magic-number compare.
    expect(isDfont(bytes)).toBe(true);
  });

  it('finds every face the family carries', () => {
    const ranges = dfontSfntRanges((o, n) => bytes.subarray(o, o + n), bytes.length);
    expect(ranges).toHaveLength(4);
    // Ascending, non-overlapping, and inside the file: the offsets came from a
    // resource map we did not write, so this is the arithmetic under test.
    let prev = 0;
    for (const r of ranges ?? []) {
      expect(r.offset).toBeGreaterThanOrEqual(prev);
      expect(r.offset + r.length).toBeLessThanOrEqual(bytes.length);
      prev = r.offset + r.length;
    }
  });

  /**
   * The end-to-end claim: every face extracts to a standalone sfnt that our
   * ordinary font reader parses. A container bug that merely shifted an offset
   * would surface here as a parse failure or a wrong name, not as a subtle
   * rendering difference.
   */
  it('extracts each face as a font with the right name', () => {
    const expected = ['Regular', 'Bold', 'Italic', 'Bold Italic'];
    for (let i = 0; i < expected.length; i++) {
      const face = extractDfontFace(bytes, i);
      const names = readFontNames(face);
      expect(names?.family).toBe('Liberation Sans');
      expect(names?.subfamily).toBe(expected[i]);
      // And it is a real font, not just a readable header.
      expect(parseSfnt(face).numGlyphs).toBeGreaterThan(2000);
    }
  });

  /**
   * A face is a `subarray`, never a rebuild — the reason `dfont.ts` exists in
   * the shape it does. Each resource is a complete sfnt whose table offsets
   * are relative to its OWN start, unlike a `.ttc`, whose are absolute into
   * the file. Asserted on real bytes: the extracted face must begin with a
   * genuine sfnt signature at its own offset zero.
   */
  it('extracts a face whose sfnt begins at its own offset zero', () => {
    const face = extractDfontFace(bytes, 2);
    const tag = (face[0] << 24 | face[1] << 16 | face[2] << 8 | face[3]) >>> 0;
    // 0x00010000 (TrueType) or 'OTTO'; Liberation is TrueType.
    expect(tag).toBe(0x00010000);
  });

  /**
   * The hazard that made extraction rather than read-in-place the design, on a
   * file written by somebody else: a face must carry no trace of a sibling.
   * Reading in place would decode perfectly and leave the whole suitcase
   * addressable, which is why `dfont.test.ts` pins this as a byte search too.
   */
  it('carries no sibling face’s name bytes into an extracted face', () => {
    const face = extractDfontFace(bytes, 0);   // Regular
    const hay = new TextDecoder('latin1').decode(face);
    expect(hay).toContain('Liberation Sans');
    expect(hay).not.toContain('BoldItalic');
  });

  it('refuses a face index the suitcase does not have', () => {
    expect(() => extractDfontFace(bytes, 4)).toThrow();
  });
});
