// Dev-only tool: mints the JBIG2 arithmetic unit-test vectors. NOT shipped, NOT
// imported by src/ or tests. Run: `node scripts/mqenc.mjs`. Every vector is
// round-tripped through the reference decoder in jbig2-codec.mjs before writing.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  MqEncoder, MqDecoder, encodeInt, decodeInt, encodeIaid, decodeIaid,
  encodeGeneric, decodeGeneric, encodeSymbolDict, decodeSymbolDict,
  encodeTextRegion, decodeTextRegion,
  encodeRefinement, decodeRefinement as refDecodeRefinement, encodeSymbolDictRefagg,
  encodePatternDict, encodeGrayscale, halftoneSkip, collectiveBitmap,
} from './jbig2-codec.mjs';

const dir = dirname(fileURLToPath(import.meta.url));
const b64 = (u8) => Buffer.from(u8).toString('base64');
const write = (name, text) => { const t = join(dir, '..', 'test', 'helpers', name); writeFileSync(t, text); console.log('wrote', t); };

// ---- integer / IAID vectors --------------------------------------------------
function encodeIntSeq(values) {
  const enc = new MqEncoder(); const cx = new Int8Array(512);
  for (const v of values) encodeInt(enc, cx, v);
  const bytes = enc.flush();
  const dec = new MqDecoder(bytes, 0, bytes.length); const dcx = new Int8Array(512);
  const got = values.map(() => decodeInt(dec, dcx));
  if (JSON.stringify(got) !== JSON.stringify(values)) throw new Error(`int round-trip mismatch: ${JSON.stringify(got)}`);
  return bytes;
}
function encodeIaidSeq(symCodeLen, values) {
  const enc = new MqEncoder(); const cx = new Int8Array(1 << (symCodeLen + 1));
  for (const v of values) encodeIaid(enc, cx, symCodeLen, v);
  const bytes = enc.flush();
  const dec = new MqDecoder(bytes, 0, bytes.length); const dcx = new Int8Array(1 << (symCodeLen + 1));
  const got = values.map(() => decodeIaid(dec, dcx, symCodeLen));
  if (JSON.stringify(got) !== JSON.stringify(values)) throw new Error(`iaid round-trip mismatch: ${JSON.stringify(got)}`);
  return bytes;
}
const smallV = [0, 1, -1, 2, -2, 100, -100, 1000];
const rangesV = [3, 4, 19, 20, 83, 84, 339, 340, 4435, 4436, 20000, -20000];
const oobV = [5, null, 7];
const iaidV = [0, 1, 17, 31];
write('jbig2-arith-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const ints_small = { bytes: b64(${JSON.stringify(b64(encodeIntSeq(smallV)))}), values: ${JSON.stringify(smallV)} };
export const ints_ranges = { bytes: b64(${JSON.stringify(b64(encodeIntSeq(rangesV)))}), values: ${JSON.stringify(rangesV)} };
export const ints_oob = { bytes: b64(${JSON.stringify(b64(encodeIntSeq(oobV)))}), values: ${JSON.stringify(oobV)} };
export const iaid_seq = { bytes: b64(${JSON.stringify(b64(encodeIaidSeq(5, iaidV)))}), symCodeLen: 5, values: ${JSON.stringify(iaidV)} };
`);

// ---- generic region vector (GB0 + TPGDON) ------------------------------------
const AT0 = [{ x: 3, y: -1 }, { x: -3, y: -1 }, { x: 2, y: -2 }, { x: -2, y: -2 }];
const GW = 16, GH = 16;
const gbm = new Uint8Array(GW * GH);
for (let y = 0; y < GH; y++) for (let x = 0; x < GW; x++)
  gbm[y * GW + x] = (x === 0 || y === 0 || x === GW - 1 || y === GH - 1 || x === y) ? 1 : 0;
gbm.copyWithin(8 * GW, 7 * GW, 8 * GW);
gbm.copyWithin(9 * GW, 8 * GW, 9 * GW);
{
  const enc = new MqEncoder(); encodeGeneric(enc, new Int8Array(1 << 16), gbm, GW, GH, 0, AT0, true);
  const bytes = enc.flush();
  const got = decodeGeneric(new MqDecoder(bytes, 0, bytes.length), new Int8Array(1 << 16), GW, GH, 0, AT0, true);
  if (Buffer.compare(Buffer.from(got), Buffer.from(gbm)) !== 0) throw new Error('generic round-trip mismatch');
  const rows = []; for (let y = 0; y < GH; y++) rows.push(Array.from(gbm.subarray(y * GW, (y + 1) * GW)).join(''));
  write('jbig2-generic-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const arith_gb0 = { bytes: b64(${JSON.stringify(b64(bytes))}), width: ${GW}, height: ${GH}, rows: ${JSON.stringify(rows)} };
`);
}

// ---- symbol dictionary vector ------------------------------------------------
const SD_AT = [{ x: 3, y: -1 }, { x: -3, y: -1 }, { x: 2, y: -2 }, { x: -2, y: -2 }];
const bar = { w: 4, h: 2, data: Uint8Array.from([1,1,1,1, 1,1,1,1]) };
const plus = { w: 3, h: 3, data: Uint8Array.from([0,1,0, 1,1,1, 0,1,0]) };
{
  const syms = [bar, plus];
  const enc = new MqEncoder(); encodeSymbolDict(enc, syms, 0, SD_AT); const bytes = enc.flush();
  const got = decodeSymbolDict(new MqDecoder(bytes, 0, bytes.length), syms.length, 0, SD_AT);
  const exp = [...syms].sort((a, b) => a.h - b.h);
  const ok = got.length === exp.length && got.every((s, k) => s.w === exp[k].w && s.h === exp[k].h && Buffer.compare(Buffer.from(s.data), Buffer.from(exp[k].data)) === 0);
  if (!ok) throw new Error('symbol dict round-trip mismatch');
  write('jbig2-symbol-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const two_syms = {
  bytes: b64(${JSON.stringify(b64(bytes))}),
  sizes: ${JSON.stringify(got.map((s) => [s.w, s.h]))},
  sym0: ${JSON.stringify(Array.from(got[0].data))},
  sym1: ${JSON.stringify(Array.from(got[1].data))},
};
`);
}

// ---- text region vector ------------------------------------------------------
{
  const trPlus = { w: 3, h: 3, data: [0,1,0, 1,1,1, 0,1,0] };
  const trBar = { w: 4, h: 2, data: [1,1,1,1, 1,1,1,1] };
  const symbols = [trPlus, trBar];
  const TRW = 12, TRH = 6, symCodeLen = Math.max(1, Math.ceil(Math.log2(symbols.length)));
  const strips = [{ dt: 1, dfs: 1, syms: [{ id: 0, curt: 0 }, { id: 1, curt: 0, ids: 4 }] }];
  const enc = new MqEncoder(); encodeTextRegion(enc, strips, symCodeLen, 1, 0); const bytes = enc.flush();
  const reg = decodeTextRegion(new MqDecoder(bytes, 0, bytes.length), TRW, TRH, 2, symbols, symCodeLen, 1, 1, 0, 0);
  const rows = []; for (let y = 0; y < TRH; y++) rows.push(Array.from(reg.subarray(y * TRW, (y + 1) * TRW)).join(''));
  write('jbig2-text-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const two_placed = {
  bytes: b64(${JSON.stringify(b64(bytes))}),
  width: ${TRW}, height: ${TRH}, numInstances: 2,
  symbols: ${JSON.stringify(symbols)},
  rows: ${JSON.stringify(rows)},
};
`);
}

// ---- generic refinement region vectors ---------------------------------------
// A refinement is a small correction to a reference, which is what it is for in
// a real file: the reference is a box, the target is the same box with a few
// pixels flipped BOTH ways, so a decoder that OR-ed rather than replaced would
// still be caught by the cleared pixels.
{
  // A centred block, NOT a box outline. TPGRON only sets LTP for a row whose
  // every pixel has a uniform 3x3 REFERENCE neighbourhood, and an outline's
  // border pixel at x=0 sits next to interior 0 on every single row — so no row
  // is ever fully typical, LTP is never set, and the TPGRON vector degenerates
  // into the plain one plus 16 wasted SLTP decisions. (Measured: the guard
  // below caught exactly that.) With a block, the blank rows above and below it
  // are genuinely typical and the mode does what it exists to do.
  const RW = 16, RH = 16;
  const refBm = new Uint8Array(RW * RH);
  for (let y = 5; y <= 10; y++) for (let x = 5; x <= 10; x++) refBm[y * RW + x] = 1;
  const target = Uint8Array.from(refBm);
  target[4 * RW + 4] = 1; target[11 * RW + 11] = 1; // added ink
  target[5 * RW + 5] = 0; target[10 * RW + 10] = 0; // cleared ink
  const REF_AT = [{ x: -1, y: -1 }, { x: -1, y: -1 }];
  const rowsOf = (bm, w, h) => { const r = []; for (let y = 0; y < h; y++) r.push(Array.from(bm.subarray(y * w, (y + 1) * w)).join('')); return r; };
  const vectors = {};
  for (const template of [0, 1]) {
    const enc = new MqEncoder();
    encodeRefinement(enc, new Int8Array(1 << 13), target, RW, RH, refBm, RW, RH, 0, 0, template, REF_AT, false);
    const bytes = enc.flush();
    const got = refDecodeRefinement(new MqDecoder(bytes, 0, bytes.length), new Int8Array(1 << 13), RW, RH, refBm, RW, RH, 0, 0, template, REF_AT, false);
    if (Buffer.compare(Buffer.from(got), Buffer.from(target)) !== 0) throw new Error(`refinement t${template} round-trip mismatch`);
    vectors[template] = { bytes, rows: rowsOf(target, RW, RH) };
  }
  const encT = new MqEncoder();
  const statsT = encodeRefinement(encT, new Int8Array(1 << 13), target, RW, RH, refBm, RW, RH, 0, 0, 0, REF_AT, true);
  const bytesT = encT.flush();
  const gotT = refDecodeRefinement(new MqDecoder(bytesT, 0, bytesT.length), new Int8Array(1 << 13), RW, RH, refBm, RW, RH, 0, 0, 0, REF_AT, true);
  if (Buffer.compare(Buffer.from(gotT), Buffer.from(target)) !== 0) throw new Error('refinement TPGRON round-trip mismatch');
  // Fail the GENERATOR, not the decoder test, if TPGRON never takes the typical
  // path: a vector that degenerated into a plain refinement would pass the
  // decoder test whatever the LTP code does. Count the LTP rows directly rather
  // than comparing encoded sizes — measured, a size comparison rejects a
  // perfectly good vector here, because for an image this small and this
  // predictable the MQ coder already spends almost nothing on a blank row and
  // the 16 SLTP decisions cost more than the typical path saves.
  if (statsT.ltpRows === 0) throw new Error('TPGRON vector sets LTP on no row — the typical path is not being exercised');
  console.log(`  TPGRON vector: ${statsT.ltpRows}/${RH} rows typical, ${bytesT.length} bytes vs ${vectors[0].bytes.length} plain`);
  write('jbig2-refine-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const refine_t0 = { bytes: b64(${JSON.stringify(b64(vectors[0].bytes))}), width: ${RW}, height: ${RH}, refRows: ${JSON.stringify(rowsOf(refBm, RW, RH))}, rows: ${JSON.stringify(vectors[0].rows)} };
export const refine_t1 = { bytes: b64(${JSON.stringify(b64(vectors[1].bytes))}), width: ${RW}, height: ${RH}, refRows: ${JSON.stringify(rowsOf(refBm, RW, RH))}, rows: ${JSON.stringify(vectors[1].rows)} };
export const refine_tpgron = { bytes: b64(${JSON.stringify(b64(bytesT))}), width: ${RW}, height: ${RH}, refRows: ${JSON.stringify(rowsOf(refBm, RW, RH))}, rows: ${JSON.stringify(rowsOf(target, RW, RH))} };
`);
}

// ---- text region with SBREFINE ----------------------------------------------
// Two instances of ONE symbol: the first placed plain, the second refined into a
// 5x5 filled block. A decoder that ignored RI would place the 4x4 box twice —
// and would also desynchronise, since the refinement's decisions are still in
// the stream.
{
  const base = { w: 4, h: 4, data: Uint8Array.from([
    1, 1, 1, 1,
    1, 0, 0, 1,
    1, 0, 0, 1,
    1, 1, 1, 1,
  ]) };
  const refined = new Uint8Array(25).fill(1); // 5x5, solid
  const RW = 16, RH = 8, symCodeLen = 1;
  const RAT = [{ x: -1, y: -1 }, { x: -1, y: -1 }];
  const strips = [{ dt: 1, dfs: 1, syms: [
    { id: 0, curt: 0 },
    { id: 0, curt: 0, ids: 4, refine: {
      rdw: 1, rdh: 1, rdx: 0, rdy: 0, w: 5, h: 5,
      target: refined, ref: base.data, refW: base.w, refH: base.h,
    } },
  ] }];
  const enc = new MqEncoder();
  encodeTextRegion(enc, strips, symCodeLen, 1, 0, true, 0, RAT);
  const bytes = enc.flush();
  const reg = decodeTextRegion(new MqDecoder(bytes, 0, bytes.length), RW, RH, 2,
    [base], symCodeLen, 1, 1, 0, 0, true, 0, RAT);
  const rowsOf = (bm, w, h) => { const r = []; for (let y = 0; y < h; y++) r.push(Array.from(bm.subarray(y * w, (y + 1) * w)).join('')); return r; };
  const out = rowsOf(reg, RW, RH);
  // Guard the FIXTURE, not the decoder: if the refined instance rendered the
  // same as the base one, the vector would prove nothing about RI. The base is
  // 4 wide with 0 either side, so only the 5-wide refinement can make '11111'.
  if (!out.some((r) => r.includes('11111'))) throw new Error('SBREFINE vector: refined instance is indistinguishable from the base symbol');

  // A SHRINKING refinement, which is the only shape that can see the floor rule.
  // T.88 offsets by (RDW >> 1) + RDX; `>>` floors toward negative infinity while
  // `(RDW / 2) | 0` truncates toward zero, and the two agree for every
  // non-negative delta — so the vector above cannot distinguish them (measured:
  // the truncating build passes it). With RDW = RDH = -1 they differ by one.
  const solid5 = new Uint8Array(25).fill(1);
  const shrunk = Uint8Array.from([
    1, 1, 1, 1,
    1, 0, 0, 1,
    1, 0, 0, 1,
    1, 1, 1, 1,
  ]);
  const SHW = 12, SHH = 8;
  const shrinkStrips = [{ dt: 1, dfs: 1, syms: [
    { id: 0, curt: 0, refine: {
      rdw: -1, rdh: -1, rdx: 0, rdy: 0, w: 4, h: 4,
      target: shrunk, ref: solid5, refW: 5, refH: 5,
    } },
  ] }];
  if (((-1 >> 1) + 0) === (((-1 / 2) | 0) + 0)) throw new Error('shrink vector: floor and truncate agree on this delta, so it cannot fence the rule');
  const shrinkEnc = new MqEncoder();
  encodeTextRegion(shrinkEnc, shrinkStrips, 1, 1, 0, true, 0, RAT);
  const shrinkBytes = shrinkEnc.flush();
  const shrinkReg = decodeTextRegion(new MqDecoder(shrinkBytes, 0, shrinkBytes.length), SHW, SHH, 1,
    [{ w: 5, h: 5, data: solid5 }], 1, 1, 1, 0, 0, true, 0, RAT);
  const shrinkOut = rowsOf(shrinkReg, SHW, SHH);
  let refaggOut = `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const refine_text = {
  bytes: b64(${JSON.stringify(b64(bytes))}),
  width: ${RW}, height: ${RH}, numInstances: 2, rTemplate: 0,
  symbols: [{ w: ${base.w}, h: ${base.h}, data: ${JSON.stringify(Array.from(base.data))} }],
  rows: ${JSON.stringify(out)},
};
export const refine_text_shrink = {
  bytes: b64(${JSON.stringify(b64(shrinkBytes))}),
  width: ${SHW}, height: ${SHH}, numInstances: 1, rTemplate: 0,
  symbols: [{ w: 5, h: 5, data: ${JSON.stringify(Array.from(solid5))} }],
  rows: ${JSON.stringify(shrinkOut)},
};
`;
  const appendVectors = (s) => { refaggOut += s; };

  // ---- symbol dictionary with SDREFAGG ---------------------------------------
  // These two vectors carry no reference-decoder round trip: there is no
  // decodeSymbolDictRefagg here, and there deliberately is not one. The expected
  // output is the KNOWN TARGET bitmap the encoder was handed, so the check that
  // matters happens in test/jbig2-refagg.test.ts, between this .mjs encoder and
  // the independently written .ts decoder — two implementations rather than one
  // file agreeing with itself.
  const box4 = { w: 4, h: 4, data: Uint8Array.from([1,1,1,1, 1,0,0,1, 1,0,0,1, 1,1,1,1]) };
  const solid4 = { w: 4, h: 4, data: new Uint8Array(16).fill(1) };
  const RAT2 = [{ x: -1, y: -1 }, { x: -1, y: -1 }];

  // REFAGGNINST == 1: one new symbol refining input symbol 0 into a solid block.
  {
    const nw = { w: 4, h: 4, data: solid4.data, refId: 0, rdx: 0, rdy: 0 };
    const enc2 = new MqEncoder();
    encodeSymbolDictRefagg(enc2, [box4], [nw], 0, RAT2);
    const bytes2 = enc2.flush();
    appendVectors(`export const refagg_one = {
  bytes: b64(${JSON.stringify(b64(bytes2))}),
  numExSyms: 1, numNewSyms: 1, rTemplate: 0,
  inputSymbols: [{ w: 4, h: 4, data: ${JSON.stringify(Array.from(box4.data))} }],
  sizes: [[4, 4]],
  syms: [${JSON.stringify(Array.from(solid4.data))}],
};
`);
  }

  // REFAGGNINST > 1: one new 8x4 symbol aggregating BOTH input symbols side by
  // side, decoded as a text region over the dictionary's current symbols.
  //
  // The symbol counts are chosen so the symCodeLen override is load-bearing:
  // the dictionary's declared total is 2 input + 1 new = 3 -> 2 bits, while the
  // count decoded so far when the aggregate runs is 2 -> 1 bit. Deriving it
  // inside decodeTextRegion reads every ID at the wrong width.
  {
    const agg = new Uint8Array(32);
    for (let y = 0; y < 4; y++) {
      for (let x = 0; x < 4; x++) {
        agg[y * 8 + x] = box4.data[y * 4 + x];
        agg[y * 8 + 4 + x] = solid4.data[y * 4 + x];
      }
    }
    const total = 2 + 1, soFar = 2;
    if (Math.ceil(Math.log2(total)) === Math.ceil(Math.log2(soFar))) {
      throw new Error('refagg_many: declared total and decoded-so-far give the same symCodeLen, so the override cannot be fenced');
    }
    const nw = { w: 8, h: 4, data: agg, agg: { initialDt: 0, strips: [
      { dt: 0, dfs: 0, syms: [{ id: 0, curt: 0 }, { id: 1, curt: 0, ids: 1 }] },
    ] } };
    const enc3 = new MqEncoder();
    encodeSymbolDictRefagg(enc3, [box4, solid4], [nw], 0, RAT2);
    const bytes3 = enc3.flush();
    appendVectors(`export const refagg_many = {
  bytes: b64(${JSON.stringify(b64(bytes3))}),
  numExSyms: 1, numNewSyms: 1, rTemplate: 0,
  inputSymbols: [
    { w: 4, h: 4, data: ${JSON.stringify(Array.from(box4.data))} },
    { w: 4, h: 4, data: ${JSON.stringify(Array.from(solid4.data))} },
  ],
  sizes: [[8, 4]],
  syms: [${JSON.stringify(Array.from(agg))}],
};
`);
  }

  // MIXED paths in ONE dictionary: a REFAGGNINST == 1 symbol followed by an
  // aggregate. This is the only shape that can observe whether the aggregate
  // text region shares the DICTIONARY's IAID/IARDX/IARDY (T.88 6.5.8.2.1) or
  // keeps its own — in refagg_one and refagg_many the other path never runs, so
  // the contexts it would have touched are in their initial state either way.
  //
  // What this vector pins is that our encoder and our decoder agree about the
  // sharing. It does NOT pin that the sharing matches T.88: both halves are
  // written from the same reading, and no independent reference is available.
  {
    const solid = { w: 4, h: 4, data: new Uint8Array(16).fill(1) };
    // Symbol A: refines input symbol 0 into a solid block (NINST == 1).
    const a = { w: 4, h: 4, data: solid.data, refId: 0, rdx: 0, rdy: 0 };
    // Symbol B: an 8x4 aggregate of input symbol 0 and the just-made symbol A.
    const agg = new Uint8Array(32);
    for (let y = 0; y < 4; y++) {
      for (let x = 0; x < 4; x++) {
        agg[y * 8 + x] = box4.data[y * 4 + x];
        agg[y * 8 + 4 + x] = solid.data[y * 4 + x];
      }
    }
    const b = { w: 8, h: 4, data: agg, agg: { initialDt: 0, strips: [
      { dt: 0, dfs: 0, syms: [{ id: 0, curt: 0 }, { id: 1, curt: 0, ids: 1 }] },
    ] } };
    const encMix = new MqEncoder();
    encodeSymbolDictRefagg(encMix, [box4], [a, b], 0, RAT2);
    const bytesMix = encMix.flush();
    appendVectors(`export const refagg_mixed = {
  bytes: b64(${JSON.stringify(b64(bytesMix))}),
  numExSyms: 2, numNewSyms: 2, rTemplate: 0,
  inputSymbols: [{ w: 4, h: 4, data: ${JSON.stringify(Array.from(box4.data))} }],
  sizes: [[4, 4], [8, 4]],
  syms: [${JSON.stringify(Array.from(solid.data))}, ${JSON.stringify(Array.from(agg))}],
};
`);
  }

  write('jbig2-refagg-vectors.ts', refaggOut);
}

// ---- halftone: pattern dictionary + grayscale planes -------------------------
// The grid vectors here TILE EXACTLY (HRX = 256*HDPW, HRY = 0), which is what
// makes the expected region hand-derivable in the test rather than needing a
// second copy of T.88's placement formula. The cross terms are deliberately not
// exercised by these vectors and are anchored by cellOrigin's own tests instead;
// the test file says so.
{
  const HDPW = 2, HDPH = 2, TEMPLATE = 0;
  // Four 2x2 cells at gray levels 0..3 — a halftone screen in miniature.
  const patterns = [
    Uint8Array.from([0, 0, 0, 0]),
    Uint8Array.from([1, 0, 0, 0]),
    Uint8Array.from([1, 0, 0, 1]),
    Uint8Array.from([1, 1, 1, 1]),
  ];
  const GRAYMAX = patterns.length - 1;
  const bpp = 2;

  // A value grid with every level present and no uniform row. It must also not
  // be Gray-invariant, or dropping the fold would leave the vector green: any
  // cell whose gray MSB is 1 (values 2 and 3) decodes differently unfolded.
  const values = Int32Array.from([
    0, 1, 2, 3,
    3, 2, 1, 0,
    1, 3, 0, 2,
    2, 0, 3, 1,
  ]);
  const GW = 4, GH = 4;
  if (!values.some((v) => (v ^ (v >> 1)) >> 1)) {
    throw new Error('halftone vector: no value has a set gray MSB, so the fold cannot be fenced');
  }
  // The generator's own check on the direction of the Gray transform: folding
  // the encoded planes back must reproduce the values. A wrong direction fails
  // HERE rather than shipping a vector that agrees with a wrong decoder.
  for (const v of values) {
    const g = v ^ (v >> 1);
    let acc = 0, above = 0;
    for (let j = bpp - 1; j >= 0; j--) { above = ((g >> j) & 1) ^ above; acc |= above << j; }
    if (acc !== v) throw new Error(`halftone vector: gray fold does not reproduce ${v}`);
  }

  const patternBytes = (() => {
    const e = new MqEncoder();
    encodePatternDict(e, new Int8Array(1 << 16), patterns, HDPW, HDPH, TEMPLATE);
    return e.flush();
  })();
  // Slicing is the only thing the pattern-dictionary vector proves that the
  // collective bitmap itself does not, so keep the collective around to say what
  // the slices came from.
  const collective = collectiveBitmap(patterns, HDPW, HDPH);

  const plainBytes = (() => {
    const e = new MqEncoder();
    encodeGrayscale(e, new Int8Array(1 << 16), values, GW, GH, bpp, TEMPLATE, undefined);
    return e.flush();
  })();

  // The skip vector: a 5-wide grid starting at HGX = -512, so column 0 lands at
  // x = -2 with a 2-wide pattern and misses the region entirely.
  const SGW = 5, SGH = 4;
  const skipGrid = {
    width: 8, height: 8, gridWidth: SGW, gridHeight: SGH,
    gridX: -512, gridY: 0, vectorX: 256 * HDPW, vectorY: 0,
    patternWidth: HDPW, patternHeight: HDPH,
  };
  const skip = halftoneSkip(skipGrid);
  // Fail the GENERATOR, not the decoder test, if the vector skips nothing: it
  // would then be a second copy of the plain one and prove nothing about
  // HENABLESKIP. Same guard shape as the TPGRON LTP-row check above.
  if (!skip.some((s) => s)) throw new Error('halftone skip vector: no cell is skipped, so the flag is not exercised');
  const skipValues = new Int32Array(SGW * SGH);
  for (let m = 0; m < SGH; m++) for (let n = 1; n < SGW; n++) skipValues[m * SGW + n] = values[m * GW + (n - 1)];
  const skipBytes = (() => {
    const e = new MqEncoder();
    encodeGrayscale(e, new Int8Array(1 << 16), skipValues, SGW, SGH, bpp, TEMPLATE, skip);
    return e.flush();
  })();
  console.log(`  halftone skip vector: ${skip.reduce((a, b) => a + b, 0)}/${SGW * SGH} cells skipped`);

  const arr = (u) => JSON.stringify(Array.from(u));
  write('jbig2-halftone-vectors.ts', `// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const patterndict = {
  bytes: b64(${JSON.stringify(b64(patternBytes))}),
  template: ${TEMPLATE}, patternWidth: ${HDPW}, patternHeight: ${HDPH}, grayMax: ${GRAYMAX},
  collectiveWidth: ${collective.width},
  patterns: ${JSON.stringify(patterns.map((p) => Array.from(p)))},
};
export const halftone_plain = {
  bytes: b64(${JSON.stringify(b64(plainBytes))}),
  width: 8, height: 8, template: ${TEMPLATE},
  gridWidth: ${GW}, gridHeight: ${GH}, gridX: 0, gridY: 0, vectorX: ${256 * HDPW}, vectorY: 0,
  patternWidth: ${HDPW}, patternHeight: ${HDPH},
  patterns: ${JSON.stringify(patterns.map((p) => Array.from(p)))},
  values: ${arr(values)},
};
export const halftone_skip = {
  bytes: b64(${JSON.stringify(b64(skipBytes))}),
  width: 8, height: 8, template: ${TEMPLATE},
  gridWidth: ${SGW}, gridHeight: ${SGH}, gridX: -512, gridY: 0, vectorX: ${256 * HDPW}, vectorY: 0,
  patternWidth: ${HDPW}, patternHeight: ${HDPH},
  patterns: ${JSON.stringify(patterns.map((p) => Array.from(p)))},
  values: ${arr(skipValues)},
  skipped: ${arr(skip)},
};
`);
}

console.log('all round-trips OK');
