// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const two_syms = {
  bytes: b64("e3Z43corvw=="),
  sizes: [[4,2],[3,3]],
  sym0: [1,1,1,1,1,1,1,1],
  sym1: [0,1,0,1,1,1,0,1,0],
};
