// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const patterndict = {
  bytes: b64("OuF/"),
  template: 0, patternWidth: 2, patternHeight: 2, grayMax: 3,
  collectiveWidth: 8,
  patterns: [[0,0,0,0],[1,0,0,0],[1,0,0,1],[1,1,1,1]],
};
export const halftone_plain = {
  bytes: b64("NTqUDQ=="),
  width: 8, height: 8, template: 0,
  gridWidth: 4, gridHeight: 4, gridX: 0, gridY: 0, vectorX: 512, vectorY: 0,
  patternWidth: 2, patternHeight: 2,
  patterns: [[0,0,0,0],[1,0,0,0],[1,0,0,1],[1,1,1,1]],
  values: [0,1,2,3,3,2,1,0,1,3,0,2,2,0,3,1],
};
export const halftone_skip = {
  bytes: b64("NTqUDQ=="),
  width: 8, height: 8, template: 0,
  gridWidth: 5, gridHeight: 4, gridX: -512, gridY: 0, vectorX: 512, vectorY: 0,
  patternWidth: 2, patternHeight: 2,
  patterns: [[0,0,0,0],[1,0,0,0],[1,0,0,1],[1,1,1,1]],
  values: [0,0,1,2,3,0,3,2,1,0,0,1,3,0,2,0,2,0,3,1],
  skipped: [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0],
};
