// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const two_placed = {
  bytes: b64("pdA="),
  width: 12, height: 6, numInstances: 2,
  symbols: [{"w":3,"h":3,"data":[0,1,0,1,1,1,0,1,0]},{"w":4,"h":2,"data":[1,1,1,1,1,1,1,1]}],
  rows: ["000000000000","001000011110","011100011110","001000000000","000000000000","000000000000"],
};
