// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const ints_small = { bytes: b64("o8hhzX9Dx/U="), values: [0,1,-1,2,-2,100,-100,1000] };
export const ints_ranges = { bytes: b64("XyUVY1k1qURswyMatrDaF3M="), values: [3,4,19,20,83,84,339,340,4435,4436,20000,-20000] };
export const ints_oob = { bytes: b64("UUc="), values: [5,null,7] };
export const iaid_seq = { bytes: b64("qXeL"), symCodeLen: 5, values: [0,1,17,31] };
