// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const refine_text = {
  bytes: b64("pdtZ+Jgx/tA="),
  width: 16, height: 8, numInstances: 2, rTemplate: 0,
  symbols: [{ w: 4, h: 4, data: [1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1] }],
  rows: ["0000000000000000","0111100011111000","0100100011111000","0100100011111000","0111100011111000","0000000011111000","0000000000000000","0000000000000000"],
};
export const refine_text_shrink = {
  bytes: b64("pde7wM0b"),
  width: 12, height: 8, numInstances: 1, rTemplate: 0,
  symbols: [{ w: 5, h: 5, data: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] }],
  rows: ["000000000000","011110000000","010010000000","010010000000","011110000000","000000000000","000000000000","000000000000"],
};
export const refagg_one = {
  bytes: b64("VVSn0/9FRw=="),
  numExSyms: 1, numNewSyms: 1, rTemplate: 0,
  inputSymbols: [{ w: 4, h: 4, data: [1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1] }],
  sizes: [[4, 4]],
  syms: [[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],
};
export const refagg_many = {
  bytes: b64("VT7RGf2GPw=="),
  numExSyms: 1, numNewSyms: 1, rTemplate: 0,
  inputSymbols: [
    { w: 4, h: 4, data: [1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1] },
    { w: 4, h: 4, data: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] },
  ],
  sizes: [[8, 4]],
  syms: [[1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1]],
};
export const refagg_mixed = {
  bytes: b64("VVSn6X/Upf9vnN8="),
  numExSyms: 2, numNewSyms: 2, rTemplate: 0,
  inputSymbols: [{ w: 4, h: 4, data: [1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1] }],
  sizes: [[4, 4], [8, 4]],
  syms: [[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], [1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1]],
};
