// GENERATED by scripts/mqenc.mjs — do not edit by hand. Regenerate: node scripts/mqenc.mjs
/* eslint-disable */
function b64(s: string): Uint8Array { return Uint8Array.from(Buffer.from(s, "base64")); }
export const arith_gb0 = { bytes: b64("BSpoCLbjreafA11zvsUIxVjydH8="), width: 16, height: 16, rows: ["1111111111111111","1100000000000001","1010000000000001","1001000000000001","1000100000000001","1000010000000001","1000001000000001","1000000100000001","1000000100000001","1000000100000001","1000000000100001","1000000000010001","1000000000001001","1000000000000101","1000000000000011","1111111111111111"] };
