/** Box generation: the styled tree to a box tree.
 *
 *  Invariant: a PURE LEAF over csscompute.js, cssprop.js, cssinline.js and
 *  htmldom.js. No Document, no Page, no PDF object module, no `node:` import.
 *
 *  Invariant: IT POSITIONS NOTHING. No x, no y, no line break, no page break.
 *  cssresolve.ts resolves a box against a width and zch2.4 hands the result to
 *  flow.ts, which does the stacking and the pagination it already does for
 *  Markdown. A step here that reaches for a coordinate is a step in the wrong
 *  issue.
 *
 *  Invariant, and the rule this module exists for: a block container holds
 *  EITHER only block-level children OR exactly one inline formatting context.
 *  Where an author mixes them the inline runs are wrapped in ANONYMOUS block
 *  boxes — which is what "block and inline formatting contexts" means.
 *
 *  Invariant: an anonymous box carries its PARENT's computed style and no
 *  element. It exists to hold inline content, so it must inherit the styling
 *  that content is in; a fresh initial style would reset the font and colour
 *  of every mixed container in a document.
 *
 *  Invariant: `display: none` generates NO BOX, rather than a box flagged
 *  invisible. A hidden subtree must not reach zch2.4, must not consume a
 *  margin, and must not take part in margin collapsing.
 *
 *  Invariant: a table box carries ROWS and CELLS, and a cell's content is
 *  built by the SAME function a paragraph's is. csstable.ts maps the result to
 *  a TableBuilder; a second content builder is how a cell would come to render
 *  bold where a paragraph renders code.
 *
 *  Invariant: CSS 2.1 §17.2.1's anonymous fixup earns its place on
 *  `display: table-*` rather than on `<table>` markup. htmltree.ts already
 *  produces well-formed `table > tbody > tr > td`, so real HTML needs almost
 *  none of it — what does need it is a div tree given table displays by CSS. */

import type { HtmlDocument, HtmlElement, HtmlNode } from './htmldom.js';
import type { ComputedStyle, UnsupportedDeclaration } from './cssprop.js';
import type { TextRun } from './textdecor.js';
import { computeStyles } from './csscompute.js';
import { inlineContentOf } from './cssinline.js';
import type { AtomicInline, FamilyResolver } from './cssinline.js';
import type { NotRendered } from './htmlreport.js';
import { elementPolicy } from './htmlreport.js';

export interface BlockBox {
  kind: 'block' | 'anonymous' | 'list-item';
  /** null for an anonymous box, which corresponds to no element. */
  el: HtmlElement | null;
  style: ComputedStyle;
  float: 'none' | 'left' | 'right';
  clear: 'none' | 'left' | 'right' | 'both';
  content:
    | { kind: 'blocks'; children: BoxNode[] }
    | { kind: 'inline'; runs: TextRun[]; atomics: AtomicInline[] };
}

/** One cell of a table box.
 *
 *  Its `content` is built by the SAME function a paragraph's is, which is what
 *  makes bold, code and a link behave identically inside a cell — mdflow.ts
 *  records the same rule for its own cells. */
export interface TableCellBox {
  /** null for an anonymous cell, generated by §17.2.1's fixup. */
  el: HtmlElement | null;
  style: ComputedStyle;
  /** >= 1. Junk clamps to 1: a NaN reaches TableBuilder and corrupts the whole
   *  grid, where 1 is the cell the author meant. */
  colSpan: number;
  rowSpan: number;
  header: boolean;
  content: BlockBox['content'];
}

export interface TableRowBox {
  /** null for an anonymous row, generated by §17.2.1's fixup. */
  el: HtmlElement | null;
  style: ComputedStyle;
  section: 'head' | 'body' | 'foot';
  cells: TableCellBox[];
}

export interface TableBox {
  kind: 'table';
  el: HtmlElement;
  style: ComputedStyle;
  float: 'none' | 'left' | 'right';
  clear: 'none' | 'left' | 'right' | 'both';
  rows: TableRowBox[];
  /** Ordinary block content, emitted BEFORE the table by cssflow.ts —
   *  TableBuilder has no caption vocabulary and dropping it loses its text. */
  caption: BoxNode | null;
}

export type BoxNode = BlockBox | TableBox;

const TABLE_DISPLAYS = new Set<ComputedStyle['display']>([
  'table', 'table-row-group', 'table-header-group', 'table-footer-group',
  'table-row', 'table-cell', 'table-caption',
]);

const BLOCK_DISPLAYS = new Set<ComputedStyle['display']>(['block', 'list-item']);

const SECTION_OF: Partial<Record<ComputedStyle['display'], 'head' | 'body' | 'foot'>> = {
  'table-header-group': 'head',
  'table-footer-group': 'foot',
  'table-row-group': 'body',
};

/** Is this node block-LEVEL, i.e. does it force its parent into a BFC? */
function isBlockLevel(n: HtmlNode, styles: Map<HtmlElement, ComputedStyle>): boolean {
  if (n.kind !== 'element') return false;
  const st = styles.get(n);
  if (st === undefined) return false;
  return BLOCK_DISPLAYS.has(st.display) || TABLE_DISPLAYS.has(st.display);
}

/** Does this node contribute anything to an inline context?
 *
 *  A text node of pure whitespace does NOT. `<div><p>a</p>\n<p>b</p></div>`
 *  has a text node between the two blocks and it collapses to nothing; an
 *  anonymous box holding one space would add a whole empty line to every
 *  prettily-indented document there is. */
function contributesInline(n: HtmlNode, styles: Map<HtmlElement, ComputedStyle>): boolean {
  if (n.kind === 'text') return n.data.trim() !== '';
  if (n.kind !== 'element') return false;
  return styles.get(n)?.display !== 'none';
}

export function buildBoxes(
  root: HtmlDocument, resolveFamily: FamilyResolver,
): { boxes: BoxNode[]; unsupported: UnsupportedDeclaration[]; report: NotRendered[] } {
  const { styles, unsupported } = computeStyles(root);
  const report: NotRendered[] = [];

  /** The `blocks | inline` content of an element, the same rule for a cell as
   *  for a paragraph. A second content builder is how a cell comes to render
   *  bold where a paragraph renders code — mdflow.ts records the same rule. */
  const contentOf = (el: HtmlElement, style: ComputedStyle): BlockBox['content'] => {
    // Does any child force a block formatting context?
    const hasBlockChild = el.children.some((c) => isBlockLevel(c, styles));

    if (!hasBlockChild) {
      const c = inlineContentOf(el.children, style, styles, resolveFamily, unsupported, report);
      return { kind: 'inline', ...c };
    }

    // A BFC. Runs of inline-level children between the block-level ones are
    // gathered into anonymous boxes.
    const children: BoxNode[] = [];
    let pending: HtmlNode[] = [];
    const flush = (): void => {
      if (!pending.some((n) => contributesInline(n, styles))) { pending = []; return; }
      const c = inlineContentOf(pending, style, styles, resolveFamily, unsupported, report);
      if (c.runs.length > 0 || c.atomics.length > 0) {
        children.push({
          kind: 'anonymous', el: null, style, float: 'none', clear: 'none',
          content: { kind: 'inline', ...c },
        });
      }
      pending = [];
    };

    for (const child of el.children) {
      if (isBlockLevel(child, styles)) {
        flush();
        const b = child.kind === 'element' ? boxFor(child) : null;
        if (b !== null) children.push(b);
        continue;
      }
      pending.push(child);
    }
    flush();

    return { kind: 'blocks', children };
  };

  /** An HTML span attribute. Junk clamps to 1: a NaN reaches TableBuilder and
   *  corrupts the whole grid, where 1 is the cell the author meant. */
  const spanAttr = (el: HtmlElement | null, name: string): number => {
    const raw = el?.attrs.get(name);
    const n = raw === undefined ? Number.NaN : Number.parseInt(raw, 10);
    return Number.isInteger(n) && n >= 1 ? n : 1;
  };

  const cellFor = (el: HtmlElement, style: ComputedStyle, inHead: boolean): TableCellBox => ({
    el,
    style,
    colSpan: spanAttr(el, 'colspan'),
    rowSpan: spanAttr(el, 'rowspan'),
    header: inHead || (el.ns === 'html' && el.name === 'th'),
    content: contentOf(el, style),
  });

  /** §17.2.1: a run of non-cell children of a row becomes ONE anonymous cell. */
  const anonCell = (
    nodes: HtmlNode[], style: ComputedStyle, inHead: boolean,
  ): TableCellBox | null => {
    if (!nodes.some((n) => contributesInline(n, styles))) return null;
    const c = inlineContentOf(nodes, style, styles, resolveFamily, unsupported, report);
    if (c.runs.length === 0 && c.atomics.length === 0) return null;
    return {
      el: null, style, colSpan: 1, rowSpan: 1, header: inHead,
      content: { kind: 'inline', ...c },
    };
  };

  const rowFor = (
    el: HtmlElement, style: ComputedStyle, section: 'head' | 'body' | 'foot',
  ): TableRowBox => {
    const cells: TableCellBox[] = [];
    let pending: HtmlNode[] = [];
    const flush = (): void => {
      const c = anonCell(pending, style, section === 'head');
      if (c !== null) cells.push(c);
      pending = [];
    };
    for (const child of el.children) {
      const st = child.kind === 'element' ? styles.get(child) : undefined;
      if (child.kind === 'element' && st !== undefined && st.display === 'table-cell') {
        flush();
        cells.push(cellFor(child, st, section === 'head'));
        continue;
      }
      pending.push(child);
    }
    flush();
    return { el, style, section, cells };
  };

  /** Collect the rows under a table or a row group, applying §17.2.1's
   *  anonymous-row fixup to a stray cell.
   *
   *  Note SECTION_OF is consulted for a nested group inside a group too; HTML
   *  does not produce that, but `display: table-row-group` on a div can. */
  const collectRows = (
    el: HtmlElement, style: ComputedStyle, section: 'head' | 'body' | 'foot',
    rows: TableRowBox[], caption: { box: BoxNode | null },
  ): void => {
    let strays: HtmlNode[] = [];
    const flushStrays = (): void => {
      const c = anonCell(strays, style, section === 'head');
      strays = [];
      if (c !== null) rows.push({ el: null, style, section, cells: [c] });
    };
    for (const child of el.children) {
      const st = child.kind === 'element' ? styles.get(child) : undefined;
      if (child.kind !== 'element' || st === undefined || st.display === 'none') {
        strays.push(child);
        continue;
      }
      if (st.display === 'table-row') {
        flushStrays();
        rows.push(rowFor(child, st, section));
        continue;
      }
      const grouped = SECTION_OF[st.display];
      if (grouped !== undefined) {
        flushStrays();
        collectRows(child, st, grouped, rows, caption);
        continue;
      }
      if (st.display === 'table-caption') {
        flushStrays();
        // A caption is ordinary block content emitted BEFORE the table;
        // TableBuilder has no caption vocabulary and dropping it would lose
        // its text.
        if (caption.box === null) {
          caption.box = {
            kind: 'block', el: child, style: st, float: 'none', clear: 'none',
            content: contentOf(child, st),
          };
        }
        continue;
      }
      strays.push(child);
    }
    flushStrays();
  };

  const boxFor = (el: HtmlElement): BoxNode | null => {
    const style = styles.get(el);
    if (style === undefined || style.display === 'none') return null;

    const float = style.float;
    const clear = style.clear;

    // What HTML says about this element's children. Applied here AND in
    // cssinline.ts's visit, because the two walks are separate: these
    // elements are inline by DEFAULT and reach that one, but `display: block`
    // routes them here, and a policy applied in only one is silent for the
    // other.
    // display:block routes an <svg> HERE rather than to cssinline.ts's visit,
    // and it must still become ONE atomic: a block-level <svg> whose children
    // were walked as content is exactly the leak zch2.7 closed. Same shape the
    // inline path produces, so cssflow.ts renders both through one branch.
    if (el.ns === 'svg' && el.name === 'svg') {
      return {
        kind: 'block', el, style, float, clear,
        content: {
          kind: 'inline', runs: [],
          atomics: [{ kind: 'svg', el, style, beforeRun: 0 }],
        },
      };
    }

    const policy = elementPolicy(el);
    if (policy !== undefined) {
      report.push({ el, kind: policy.kind, construct: policy.construct });
      if (policy.content === 'suppress') {
        // A BOX with no content rather than NO box: the element is still a
        // replaced box that occupies its margins, unlike `display: none`.
        // cssmargin.ts's isEmpty then treats it as an empty block, which is
        // what a browser does with an iframe it cannot load.
        return {
          kind: 'block', el, style, float, clear,
          content: { kind: 'inline', runs: [], atomics: [] },
        };
      }
    }

    if (TABLE_DISPLAYS.has(style.display)) {
      const rows: TableRowBox[] = [];
      const caption: { box: BoxNode | null } = { box: null };
      // A stray table-row / table-cell reached directly is itself wrapped:
      // collectRows treats THIS element as the table, so a cell child lands
      // in an anonymous row, which is §17.2.1's answer.
      collectRows(el, style, 'body', rows, caption);
      return { kind: 'table', el, style, float, clear, rows, caption: caption.box };
    }

    const kind: BlockBox['kind'] = style.display === 'list-item' ? 'list-item' : 'block';
    return { kind, el, style, float, clear, content: contentOf(el, style) };
  };

  // The DOCUMENT ELEMENT is the root box, not the document: a document is not
  // a box and has no style.
  const docEl = root.children.find((c): c is HtmlElement => c.kind === 'element');
  const boxes: BoxNode[] = [];
  if (docEl !== undefined) {
    const b = boxFor(docEl);
    if (b !== null) boxes.push(b);
  }
  return { boxes, unsupported, report };
}
